### ISSUE TITLE
New-NessusProfile - Outfile Error

### ISSUE THREAD

**Issue by leonardjohnsonjr** [vignatenko/NessusPowerShell#1]
New-NessusProfile : Could not load file or assembly
'System.Security.Cryptography.ProtectedData, Version=0.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
At line:1 char:1
+ New-NessusProfile -OutFile c:\test.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-NessusProfile], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,NessusPowerShell.Commands.NewNessusProfile

**Comment by vignatenko** [comment]
@leonardjohnsonjr 
Please give me more details:
- do you use .msi or you've built the assembly by yourself?
- on what OS you are encountering this issue?
- have you tried to start cmd-let under elevated privileges?

**Comment by leonardjohnsonjr** [comment]
I am using the msi.
Win 7 x64
I right clicked -> Run As Administrator on PS
I then tried to build the assembly myself with the same result. I then downloaded PS 6 beta with same results.

**Comment by vignatenko** [comment]
Well, I've downloaded the .msi and tried it on test machine with  Windows Server 2012R2 - no issues.
It may  be issue with PS 6 beta (here is one [ reported](https://github.com/PowerShell/PowerShell/issues/4367))

On my  test machine I have

PS version 4 
```
PS > $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1`
```

and .NET Runtime 4.5

```
PS> Get-ChildItem "hklm:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\"

    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full


Name                           Property
----                           --------
1033                           Version       : 4.5.51641
                               CBS           : 1
                               TargetVersion : 4.0.0
                               Install       : 1
                               Servicing     : 0
                               Release       : 378675

```
Can you please confirm that you have .Net Runtime 4.5 installed.
Just run this command:
```
PS> Get-ChildItem "hklm:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\"
```

In the mean time I'm going to test it on VM with Win7x 86 (from [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)).

**Comment by leonardjohnsonjr** [comment]
I installed PS 4. My .NET Framework is targeting 4.6. I am now able to save the profile however it tells me when I attempt to issue Test-NessusProfile (Status) The underlying connection was clo...
I am able to log directly into the website with no issues. Would I be able to send you a "test" profile so that you can verify everything is saving correctly?

**Comment by leonardjohnsonjr** [comment]
New-NessusProfile -OutFile %UserProfile%\Documents\NessusPowerShell\Profiles\nessus.profile.txt
When I look into My Documents folder, NessusPowerShell folder does not exist.
![image](https://user-images.githubusercontent.com/3433936/29619788-f95f7590-87e9-11e7-85b6-e4e9b17f2c57.png)
![image](https://user-images.githubusercontent.com/3433936/29619913-54e1565e-87ea-11e7-81cd-6f848b51dc50.png)
Is there a debug version that I can use that would log everything to a file?

**Comment by vignatenko** [comment]
Regarding to your command 
```
New-NessusProfile -OutFile %UserProfile%\Documents\NessusPowerShell\Profiles\nessus.profile.txt
```
The file will be created in folder c:\Users\ljohnson\\%UserProfile%\Documents\NessusPowerShell\Profiles\nessus.profile.txt.

This is a  bug. Thank you for finding it!

While this bug exists, please, use absolute path without placeholders:
```
New-NessusProfile -OutFile c:\temp\nessus.profile.txt
```
There is no "debug" version.

I'm going to deploy fixed version next week.

**Comment by leonardjohnsonjr** [comment]
Even with hardcoding the path to the profile I receive 'The underlying connection was closed: An unexpected error occurred on a send." Would it be possible to connect to a 'test' Nessus server to verify that everything is functioning correctly on my system?

**Comment by vignatenko** [comment]
Yes, it will be possible next week(I am on leave until next  week). Did you specify server and port correctly?

**Comment by leonardjohnsonjr** [comment]
Powershell requests the Server value to which I put only the server name and not the port. When I include the port, and Test-NessusProfile I receive Invalud URI: The hostname could not be parsed. It seems that when I do not include the port number it defaults to 8834. You may want to update this so if a user passes the port number with the server name, it will use that instead.

**Comment by leonardjohnsonjr** [comment]
I am actually getting a bit further along the process. When I pass in the IP address it states: "The remote server returned an error: (401) Unauthorized." So there must be one more piece that is missing. So close!!!

**Comment by vignatenko** [comment]
Please, try new fixed version [x64](https://github.com/vignatenko/NessusPowerShell/releases/download/v1.0.2/NessusPowerShellModule-x64.msi). 
Use -Verbose flag  - it will show more information.

**Comment by leonardjohnsonjr** [comment]
Please be aware that the installation package will not allow me to ‘upgrade’ to this fixed version. I have to uninstall/install.

 

 

Thank you,

 

Lenny Johnson

 

3MergingDesign

80 Gordon St., Ridgefield Park NJ, 07660

phone | 201.500.7072 

website | www.3mergingdesign.com <http://www.3mergingdesign.com/>

**Comment by vignatenko** [comment]
Thanks, I'm aware. I will change it.
If you're feeling  it is critical, please, post new bug.
